[package]
name = "adof"
version = "0.1.0"
edition = "2021"
authors = ["Abinash S. <fnabinash@gmail.com>"] 
license = "MIT"
description = "ADOF - An Automatic Dot-files Organizer Friend"
readme = "README.md"
homepage = "https://github.com/fnabinash/adof"
repository = "https://github.com/fnabinash/adof"
keywords = ["dotfiles", "adof", "dotfile-manager", "vim", "neovim"]
categories = ["command-line-utilities"]

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
git2 = "0.19.0"
glob = "0.3.1"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
unicode-width = "0.2.0"
walkdir = "2.5.0"
webbrowser = "1.0.2"
