[package]
name = "adof"
version = "0.10.0"
edition = "2021"
authors = ["Abinash S. <fnabinash@gmail.com>"] 
license = "MIT"
description = "ADOF - An Automatic Dot-files Organizer Friend"
readme = "README.md"
homepage = "https://github.com/fnabinash/adof"
repository = "https://github.com/fnabinash/adof"
keywords = ["config", "adof", "config-management", "vim", "neovim"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.93"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
git2 = "0.19.0"
glob = "0.3.1"
reqwest = "0.12.9"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
sha2 = "0.10.8"
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
webbrowser = "1.0.2"
